/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out of this device. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out everywhere else. */
        post: operations["logout_others"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who am I, and which workspaces can I see. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the display name shown on the speaking card and attendance list. */
        patch: operations["update_profile"];
        trace?: never;
    };
    "/api/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a one-time sign-in code by email. */
        post: operations["request_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active sessions for this account. */
        get: operations["sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a code for a session. Consumes the code; bounded attempts. */
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed (or reset) the demo workspace for the calling account. Development only. */
        post: operations["seed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Development inbox: messages captured by the in-memory mail transport. Never available with SMTP. */
        get: operations["inbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview an invitation. Safe without a session: reveals only a masked address. */
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invitation with a session whose verified email matches. Single use. */
        post: operations["accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/capture-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where should a new thought go? Powers the bookmarkable /capture route. */
        get: operations["capture_target"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A sprint as seen by the caller. Never includes per-person contribution status. */
        get: operations["get"];
        put?: never;
        post?: never;
        /** Delete a draft sprint. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Update sprint setup. Privacy/AI choices lock once collection starts. */
        patch: operations["update"];
        trace?: never;
    };
    "/api/sprints/{sprint_id}/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** AI preparation status, jobs and proposals for this sprint. */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/ai/grouping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask for a grouping draft. Idempotent per input snapshot; runs in the background. */
        post: operations["request_grouping"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/ai/proposals/{proposal_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn a proposal into editable themes. Explicit; never automatic. */
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/ai/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a proposal (kept for the record, hidden from the studio). */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone's entries, revealed as a batch after collection closes. Anonymous; randomised order. */
        get: operations["shared"];
        put?: never;
        /** Save a thought. Only while collection is open; only visible to you until it closes. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/entries/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your own entries for this sprint, on any device. */
        get: operations["mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete one of your entries while collection is open. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Edit one of your entries while collection is open. */
        patch: operations["update"];
        trace?: never;
    };
    "/api/sprints/{sprint_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live hints for a sprint. Authorization is re-checked periodically; a
         *     revoked member's stream ends within one heartbeat.
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiments for this sprint. */
        get: operations["list"];
        put?: never;
        /** Propose an experiment. The nominated owner must accept before it counts. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/experiments/previous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiments carried from earlier sprints ("Last time, we said…"). */
        get: operations["previous"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a proposed experiment. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Edit an experiment or record its outcome. Facilitators of the sprint and the owner may edit. */
        patch: operations["update"];
        trace?: never;
    };
    "/api/sprints/{sprint_id}/experiments/{experiment_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The nominated owner accepts (or declines) ownership. */
        post: operations["accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CSV export. Summary: one row per theme. Raw: one row per entry. */
        get: operations["csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/export.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markdown export. */
        get: operations["markdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Personal reminder preference for this sprint. */
        patch: operations["my_prefs"];
        trace?: never;
    };
    "/api/sprints/{sprint_id}/meeting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The stage as the caller may see it. Same shape for participants, facilitator and presenter. */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/meeting/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Your own attendance and readiness. */
        post: operations["attendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/meeting/attendance/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Facilitator: mark someone present or absent. */
        post: operations["attendance_for"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/meeting/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Facilitator commands. Applied only if `expected_version` matches the stage. */
        post: operations["command"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/meeting/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add anonymous context to a theme during the meeting. Released in batches by the facilitator. */
        post: operations["add_context"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/meeting/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Controller heartbeat. Keeps the "who controls the stage" indicator honest. */
        post: operations["heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/meeting/notes/{theme_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Facilitator's discussion notes for a theme. */
        put: operations["notes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/meeting/pass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pass your turn (only meaningful when the card shows you). */
        post: operations["pass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a workspace member to the sprint. */
        post: operations["add_participant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/participants/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a participant. Sealed entries they already saved stay in the sprint pool. */
        delete: operations["remove_participant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/recap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The meeting recap. Participants see it once published; the facilitator always. */
        get: operations["get_recap"];
        /** Save, regenerate, or publish the recap. Publishing is explicit. */
        put: operations["put_recap"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Themes, their entries, and the ungrouped pool. Available once collection has closed. */
        get: operations["get"];
        put?: never;
        /** Create a theme, optionally with entries. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/themes/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder themes. Not structural: does not reset voting. */
        post: operations["reorder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/themes/ungroup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move entries back to the ungrouped pool. */
        post: operations["ungroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/themes/{theme_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a theme; its entries return to the ungrouped pool. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Edit a theme's text and flags. Text edits don't reset voting; entry changes do. */
        patch: operations["update"];
        trace?: never;
    };
    "/api/sprints/{sprint_id}/themes/{theme_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge this theme into another. Text of the target is kept; entries move. */
        post: operations["merge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/themes/{theme_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Split entries out of a theme into a new one. */
        post: operations["split"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move the sprint through its lifecycle. Every transition is checked server-side. */
        post: operations["transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voting state for the caller: open round with private remaining budget, closed rounds with totals. */
        get: operations["get"];
        put?: never;
        /** Cast or withdraw a vote. At most one per theme; budget enforced transactionally. */
        post: operations["cast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/votes/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open a voting round over the current theme set. Freezes grouping until closed or cancelled. */
        post: operations["open_round"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/{sprint_id}/votes/rounds/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close (reveal totals) or cancel the open round. */
        post: operations["close_round"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a workspace. The creator becomes its owner. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace details: settings, members, pending invitations. */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update workspace settings (owner only). */
        patch: operations["update"];
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent facilitator/owner actions. Contains resource ids, never content. */
        get: operations["audit_log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace-wide experiment history. */
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite a teammate by email. Sends a link; joining requires verifying that address. */
        post: operations["invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a pending invitation. */
        delete: operations["revoke_invitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/members/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member. Their sessions keep working elsewhere but every request to this workspace fails from now on. */
        delete: operations["revoke_member"];
        options?: never;
        head?: never;
        /** Promote or demote a member (owner only). */
        patch: operations["set_role"];
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/sprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sprints in a workspace, newest first. */
        get: operations["list"];
        put?: never;
        /** Create a sprint (owners and members can create; the creator or the chosen facilitator runs it). */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process is up. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: the database answers. */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptBody: {
            accept: boolean;
        };
        AcceptResponse: {
            /** Format: uuid */
            sprint_id?: string | null;
            /** Format: uuid */
            workspace_id: string;
        };
        AgendaInput: {
            reason?: string | null;
            /** Format: uuid */
            theme_id: string;
        };
        AgendaItem: {
            reason?: string | null;
            /** Format: uuid */
            theme_id: string;
        };
        AiJobView: {
            /** Format: date-time */
            created_at: string;
            error_summary?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: uuid */
            id: string;
            model?: string | null;
            provider: string;
            status: string;
        };
        AiProposalView: {
            /** Format: date-time */
            applied_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            job_id: string;
            proposal: components["schemas"]["Proposal"];
            /** Format: date-time */
            rejected_at?: string | null;
        };
        AiStatus: {
            /** @description A provider is configured on this server. */
            available: boolean;
            /** @description This sprint opted in before collection started. */
            enabled: boolean;
            explanation: string;
            jobs: components["schemas"]["AiJobView"][];
            proposals: components["schemas"]["AiProposalView"][];
            provider: string;
        };
        ApplyBody: {
            /** @description "replace" clears existing themes first; "add" appends the draft's themes. */
            mode: string;
            reset_voting_reason?: string | null;
        };
        AttendanceBody: {
            present?: boolean | null;
            /** @description true = "Ready to speak", false = "Pass for now". */
            ready?: boolean | null;
        };
        AttendeeView: {
            /** Format: uuid */
            account_id: string;
            display_name: string;
            is_facilitator: boolean;
            is_you: boolean;
            present: boolean;
            /** @description Only shown to the facilitator and to the person themself. */
            ready?: boolean | null;
        };
        AuditEvent: {
            action: string;
            actor_name?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            meta: unknown;
            /** Format: uuid */
            sprint_id?: string | null;
        };
        CaptureTarget: {
            /** @description Sprints currently collecting that the caller participates in, most recently opened first. */
            collecting: components["schemas"]["SprintSummary"][];
            /** @description Sprints the caller participates in that are past collection but not finished (retro soon or live). */
            upcoming: components["schemas"]["SprintSummary"][];
        };
        CastBody: {
            /** @description true to add a vote, false to take it back. */
            cast: boolean;
            /** Format: uuid */
            theme_id: string;
        };
        CloseBody: {
            /** @description "close" reveals totals; "cancel" discards the round. */
            action: string;
            reason?: string | null;
        };
        Command: {
            phase: string;
            /** @enum {string} */
            type: "set_phase";
        } | {
            /** Format: uuid */
            theme_id?: string | null;
            /** @enum {string} */
            type: "set_topic";
        } | {
            items: components["schemas"]["AgendaInput"][];
            /** @enum {string} */
            type: "set_agenda";
        } | {
            plan: unknown;
            /** @enum {string} */
            type: "set_plan";
        } | {
            /** Format: int64 */
            secs: number;
            /** @enum {string} */
            type: "timer_start";
        } | {
            /** @enum {string} */
            type: "timer_pause";
        } | {
            /** @enum {string} */
            type: "timer_resume";
        } | {
            /** Format: int64 */
            delta_secs: number;
            /** @enum {string} */
            type: "timer_adjust";
        } | {
            /** @enum {string} */
            type: "timer_clear";
        } | {
            /** @enum {string} */
            type: "take_control";
        } | {
            /** @enum {string} */
            type: "speaking_start";
        } | {
            /** @enum {string} */
            type: "speaking_next";
        } | {
            /** @enum {string} */
            type: "speaking_open_floor";
        } | {
            /** @enum {string} */
            type: "speaking_end";
        } | {
            /** @enum {string} */
            type: "release_context";
        } | {
            /** Format: int64 */
            secs: number;
            /** @enum {string} */
            type: "quiet_reading";
        } | {
            discussed: boolean;
            /** Format: uuid */
            theme_id: string;
            /** @enum {string} */
            type: "mark_discussed";
        };
        CommandBody: {
            command: components["schemas"]["Command"];
            /**
             * Format: int64
             * @description The stage version the client last saw. Mismatch → 409, refetch.
             */
            expected_version: number;
        };
        ContextBody: {
            body: string;
            idempotency_key?: string | null;
            /** Format: uuid */
            theme_id: string;
        };
        ContextNote: {
            body: string;
            /** Format: uuid */
            id: string;
        };
        CreateSprintBody: components["schemas"]["SprintSchedule"] & {
            ai_processing: boolean;
            external_ref?: string | null;
            /** Format: uuid */
            facilitator_id: string;
            goal?: string | null;
            include_facilitator_in_rotation?: boolean | null;
            name: string;
            /** @description Optional brief opening question for the retro's first minutes. */
            opening_question?: string | null;
            participant_ids: string[];
            reminders_enabled: boolean;
            /** Format: int32 */
            vote_budget?: number | null;
        };
        CreateWorkspaceBody: {
            name: string;
        };
        DemoSeeded: {
            /** Format: uuid */
            previous_sprint_id: string;
            /** Format: uuid */
            sprint_id: string;
            /** Format: uuid */
            workspace_id: string;
        };
        DiscussionNotes: {
            could_try: string;
            discussed: boolean;
            impact: string;
            notes: string;
            what_happened: string;
        };
        EntryBody: {
            body: string;
            /** @description Optional. A thought without a category is "unsorted" and can be sorted later. */
            category?: string | null;
            /** @description Client-generated key so retries after a dropped connection don't duplicate. */
            idempotency_key?: string | null;
            impact?: string | null;
            might_help?: string | null;
            period?: string | null;
        };
        EntryIdsBody: {
            entry_ids: string[];
            reset_voting_reason?: string | null;
        };
        ErrorBody: {
            code: string;
            error: string;
        };
        Experiment: {
            change_to_try: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            outcome_note?: string | null;
            owner_accepted: boolean;
            /** Format: uuid */
            owner_account_id?: string | null;
            owner_name?: string | null;
            /** Format: date */
            review_on: string;
            /** Format: date-time */
            reviewed_at?: string | null;
            /** Format: uuid */
            sprint_id: string;
            sprint_name: string;
            status: string;
            success_signal: string;
            /** Format: uuid */
            theme_id?: string | null;
            theme_title?: string | null;
        };
        ExperimentBody: {
            change_to_try: string;
            /** @description Required to create more than three experiments in one sprint. */
            override_limit?: boolean | null;
            /** Format: uuid */
            owner_account_id?: string | null;
            /** Format: date */
            review_on?: string | null;
            success_signal: string;
            /** Format: uuid */
            theme_id?: string | null;
        };
        GroupingView: {
            can_edit: boolean;
            /** Format: int64 */
            grouping_revision: number;
            sprint_status: string;
            themes: components["schemas"]["ThemeView"][];
            /** Format: int64 */
            total_entries: number;
            ungrouped: components["schemas"]["SharedEntry"][];
            voting_open: boolean;
        };
        Health: {
            ai_provider: string;
            database: string;
            email_transport: string;
            status: string;
            /** Format: int64 */
            uptime_secs: number;
        };
        InboxMessage: {
            body: string;
            subject: string;
            to: string;
        };
        InvitationPreview: {
            /** @description Masked recipient, e.g. "j•••@example.com". */
            email_hint?: string | null;
            matches_session: boolean;
            signed_in: boolean;
            valid: boolean;
            /** @description Only present when the caller's verified email matches the invitation. */
            workspace_name?: string | null;
        };
        InviteBody: {
            email: string;
            /**
             * Format: uuid
             * @description Add the invitee to this sprint once they join.
             */
            sprint_id?: string | null;
        };
        InviteResponse: {
            already_member: boolean;
            email: string;
            /** Format: uuid */
            invitation_id: string;
        };
        Me: {
            /** Format: uuid */
            account_id: string;
            ai_provider: string;
            display_name: string;
            email: string;
            email_transport: string;
            /** Format: date-time */
            session_expires_at: string;
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
        MemberInfo: {
            /** Format: uuid */
            account_id: string;
            display_name: string;
            /** @description Present for workspace owners only. */
            email?: string | null;
            is_you: boolean;
            /** Format: date-time */
            joined_at: string;
            role: string;
        };
        MergeBody: {
            /** Format: uuid */
            into_theme_id: string;
            reset_voting_reason?: string | null;
        };
        MyContext: {
            body: string;
            /** Format: uuid */
            id: string;
            released: boolean;
            /** Format: uuid */
            theme_id?: string | null;
        };
        MyEntry: {
            body: string;
            category?: string | null;
            /** Format: date-time */
            created_at: string;
            editable: boolean;
            /** Format: uuid */
            id: string;
            impact?: string | null;
            might_help?: string | null;
            period?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        MyPrefsBody: {
            reminders_opt_out: boolean;
        };
        NotesBody: {
            could_try?: string | null;
            impact?: string | null;
            notes?: string | null;
            what_happened?: string | null;
        };
        Ok: {
            ok: boolean;
        };
        OpenRoundBody: {
            /**
             * Format: int32
             * @description Votes per person; defaults to the sprint setting.
             */
            budget?: number | null;
        };
        Participant: {
            /** Format: uuid */
            account_id: string;
            display_name: string;
            is_facilitator: boolean;
            is_you: boolean;
        };
        ParticipantBody: {
            /** Format: uuid */
            account_id: string;
        };
        PendingInvitation: {
            /** Format: date-time */
            created_at: string;
            email: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sprint_id?: string | null;
        };
        Proposal: {
            /** @description Coverage/opposition notes for the facilitator. */
            notes?: string[];
            themes: components["schemas"]["ProposedTheme"][];
            ungrouped_entry_ids: string[];
        };
        ProposedTheme: {
            draft_experiment?: string | null;
            entry_ids: string[];
            question: string;
            /** @description Optional neutral rephrasings keyed by entry id. Never replace originals. */
            rephrasings?: {
                [key: string]: string;
            };
            summary: string;
            title: string;
        };
        Recap: {
            /** Format: date-time */
            approved_at?: string | null;
            body: string;
            draft_source: string;
            exists: boolean;
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        RecapBody: {
            /** @description Replace the recap text. Omit to regenerate a draft from the meeting record. */
            body?: string | null;
            publish?: boolean | null;
        };
        ReorderBody: {
            /** @description Shown when the order departs from vote totals. */
            reason?: string | null;
            theme_ids: string[];
        };
        RequestCodeBody: {
            email: string;
        };
        RequestCodeResponse: {
            /** Format: int64 */
            expires_in_minutes: number;
            /** @description Always true when the request was accepted; existence of an account is never revealed. */
            sent: boolean;
        };
        ResetBody: {
            reset_voting_reason?: string | null;
        };
        RoleBody: {
            role: string;
        };
        SessionInfo: {
            /** Format: date-time */
            created_at: string;
            current: boolean;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_seen_at: string;
        };
        /** @description The shared, anonymous representation. Add fields here with care. */
        SharedEntry: {
            body: string;
            category?: string | null;
            /** Format: uuid */
            id: string;
            impact?: string | null;
            might_help?: string | null;
            period?: string | null;
            /** Format: uuid */
            theme_id?: string | null;
        };
        SpeakerView: {
            /** Format: uuid */
            account_id: string;
            display_name: string;
            is_you: boolean;
        };
        SpeakingView: {
            current?: null | components["schemas"]["SpeakerView"];
            prompt: string;
            /** Format: int64 */
            remaining: number;
            /** Format: uuid */
            round_id: string;
            status: string;
        };
        SplitBody: {
            entry_ids: string[];
            reset_voting_reason?: string | null;
            title: string;
        };
        SprintDetail: components["schemas"]["SprintSummary"] & {
            ai_locked: boolean;
            ai_processing: boolean;
            ai_provider: string;
            allowed_transitions: string[];
            /** Format: date-time */
            collection_closed_at?: string | null;
            /** Format: date-time */
            collection_opened_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            content_purged_at?: string | null;
            /**
             * Format: int64
             * @description Aggregate only, and only once collection has closed.
             */
            entry_count?: number | null;
            /** Format: int64 */
            grouping_revision: number;
            has_session: boolean;
            include_facilitator_in_rotation: boolean;
            my_reminders_opt_out: boolean;
            opening_question?: string | null;
            participants: components["schemas"]["Participant"][];
            /** Format: uuid */
            previous_sprint_id?: string | null;
            reminders_enabled: boolean;
            /** Format: int32 */
            reopened_count: number;
            revealed_once: boolean;
            role: string;
            session_cancelled: boolean;
            /** Format: int64 */
            theme_count: number;
            /** Format: int32 */
            vote_budget: number;
            workspace_name: string;
        };
        SprintSchedule: {
            /** Format: date */
            ends_on: string;
            /**
             * Format: date
             * @description Local calendar date of the retro in `timezone`.
             */
            retro_date: string;
            /** Format: int32 */
            retro_duration_min: number;
            /** @description Local wall time, "HH:MM". */
            retro_time: string;
            /** Format: date */
            starts_on: string;
            timezone: string;
        };
        SprintSummary: {
            /** Format: date */
            ends_on: string;
            external_ref?: string | null;
            facilitator_name?: string | null;
            goal?: string | null;
            /** Format: uuid */
            id: string;
            is_facilitator: boolean;
            is_participant: boolean;
            name: string;
            /** Format: int64 */
            participant_count: number;
            /** Format: date-time */
            retro_at: string;
            /** Format: int32 */
            retro_duration_min: number;
            retro_local: string;
            /** Format: date */
            starts_on: string;
            status: string;
            timezone: string;
            /** Format: uuid */
            workspace_id: string;
        };
        StageSnapshot: {
            agenda: components["schemas"]["AgendaItem"][];
            attendance: components["schemas"]["AttendeeView"][];
            cancelled: boolean;
            controller_name?: string | null;
            controller_stale: boolean;
            /** Format: uuid */
            current_theme_id?: string | null;
            discussed_theme_ids: string[];
            /** Format: date-time */
            ended_at?: string | null;
            /** @description Facilitator only: there is context waiting to be released. */
            has_unreleased_context?: boolean | null;
            include_facilitator_in_rotation: boolean;
            is_facilitator: boolean;
            my_context: components["schemas"]["MyContext"][];
            notes: components["schemas"]["DiscussionNotes"];
            opening_question?: string | null;
            phase: string;
            phases: string[];
            plan: unknown;
            /** @description A short silent-reading pause is running: the stage stays quiet. */
            quiet_reading: boolean;
            /** Format: int32 */
            retro_duration_min: number;
            /** Format: date-time */
            server_time: string;
            /** Format: uuid */
            session_id: string;
            speaking?: null | components["schemas"]["SpeakingView"];
            /** Format: date-time */
            started_at: string;
            timer: components["schemas"]["TimerView"];
            /** Format: int64 */
            version: number;
            you_control: boolean;
        };
        ThemeBody: {
            draft_experiment?: string | null;
            entry_ids?: string[] | null;
            needs_attention?: boolean | null;
            order_reason?: string | null;
            parked?: boolean | null;
            question?: string | null;
            /** @description Required when the change alters the theme set while a vote round is open. */
            reset_voting_reason?: string | null;
            summary?: string | null;
            title?: string | null;
        };
        ThemeView: {
            category_mix: {
                [key: string]: number;
            };
            /** @description Released anonymous context added during the meeting. */
            context: components["schemas"]["ContextNote"][];
            draft_experiment?: string | null;
            entries: components["schemas"]["SharedEntry"][];
            /**
             * Format: int64
             * @description Number of entries — entries, not people.
             */
            entry_count: number;
            /** Format: uuid */
            id: string;
            needs_attention: boolean;
            order_reason?: string | null;
            parked: boolean;
            /** Format: int32 */
            position: number;
            question: string;
            source: string;
            summary: string;
            title: string;
            /**
             * Format: int64
             * @description Vote total from the most recent closed round, if any.
             */
            votes?: number | null;
        };
        TimerView: {
            /** Format: date-time */
            ends_at?: string | null;
            /** Format: int64 */
            remaining_secs: number;
            running: boolean;
            /** Format: int64 */
            total_secs: number;
        };
        TransitionBody: {
            /** @description Required for closing collection (it reveals feedback) and reopening it. */
            confirm?: boolean | null;
            to: string;
        };
        UpdateExperimentBody: {
            change_to_try?: string | null;
            outcome_note?: string | null;
            /** Format: uuid */
            owner_account_id?: string | null;
            /** Format: date */
            review_on?: string | null;
            status?: string | null;
            success_signal?: string | null;
        };
        UpdateProfileBody: {
            display_name: string;
        };
        UpdateSprintBody: {
            /** @description Only honoured while the sprint is a draft (privacy choices lock at collection start). */
            ai_processing?: boolean | null;
            external_ref?: string | null;
            /** Format: uuid */
            facilitator_id?: string | null;
            goal?: string | null;
            include_facilitator_in_rotation?: boolean | null;
            name?: string | null;
            opening_question?: string | null;
            reminders_enabled?: boolean | null;
            schedule?: null | components["schemas"]["SprintSchedule"];
            /** Format: int32 */
            vote_budget?: number | null;
        };
        UpdateWorkspaceBody: {
            ai_enabled_default?: boolean | null;
            name?: string | null;
            /** Format: int32 */
            outcome_retention_days?: number | null;
            /** Format: int32 */
            retention_days?: number | null;
        };
        VerifyBody: {
            code: string;
            /** @description Used only when this email has no account yet. */
            display_name?: string | null;
            email: string;
        };
        VoteRoundView: {
            /** Format: int32 */
            budget: number;
            cancel_reason?: string | null;
            /** Format: date-time */
            closed_at?: string | null;
            /** @description True when you are eligible to vote (a participant; facilitators vote too). */
            eligible: boolean;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            my_remaining: number;
            /** @description Your own choices in this round. Private. */
            my_votes: string[];
            /** Format: date-time */
            opened_at: string;
            status: string;
            /** @description Totals per theme, only after the round has closed. */
            totals?: {
                [key: string]: number;
            } | null;
        };
        VotingState: {
            current?: null | components["schemas"]["VoteRoundView"];
            previous: components["schemas"]["VoteRoundView"][];
        };
        Workspace: {
            ai_enabled_default: boolean;
            ai_provider: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            is_demo: boolean;
            name: string;
            /** Format: int32 */
            outcome_retention_days: number;
            /** Format: int32 */
            retention_days: number;
            role: string;
        };
        WorkspaceDetail: {
            can_invite: boolean;
            members: components["schemas"]["MemberInfo"][];
            pending_invitations: components["schemas"]["PendingInvitation"][];
            workspace: components["schemas"]["Workspace"];
        };
        WorkspaceSummary: {
            /** Format: uuid */
            id: string;
            is_demo: boolean;
            name: string;
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    logout_others: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    request_code: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCodeResponse"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    seed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSeeded"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    inbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxMessage"][];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreview"];
                };
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    capture_target: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureTarget"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintDetail"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSprintBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintDetail"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiStatus"];
                };
            };
        };
    };
    request_grouping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiStatus"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupingView"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiStatus"];
                };
            };
        };
    };
    shared: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedEntry"][];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyEntry"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    mine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyEntry"][];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyEntry"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of {resource, at} hints */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    previous: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExperimentBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    csv: {
        parameters: {
            query?: {
                /** @description "summary" (default) or "raw". */
                scope?: string | null;
            };
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/csv */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markdown: {
        parameters: {
            query?: {
                /** @description "summary" (default) or "raw". */
                scope?: string | null;
            };
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/markdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    my_prefs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MyPrefsBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageSnapshot"];
                };
            };
        };
    };
    attendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageSnapshot"];
                };
            };
        };
    };
    attendance_for: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageSnapshot"];
                };
            };
        };
    };
    command: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageSnapshot"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    add_context: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageSnapshot"];
                };
            };
        };
    };
    heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageSnapshot"];
                };
            };
        };
    };
    notes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                theme_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageSnapshot"];
                };
            };
        };
    };
    pass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageSnapshot"];
                };
            };
        };
    };
    add_participant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    remove_participant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    get_recap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recap"];
                };
            };
        };
    };
    put_recap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecapBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recap"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupingView"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThemeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupingView"];
                };
            };
        };
    };
    reorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupingView"];
                };
            };
        };
    };
    ungroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryIdsBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupingView"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                theme_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupingView"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                theme_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThemeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupingView"];
                };
            };
        };
    };
    merge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                theme_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupingView"];
                };
            };
        };
    };
    split: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                theme_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupingView"];
                };
            };
        };
    };
    transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintDetail"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VotingState"];
                };
            };
        };
    };
    cast: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CastBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VotingState"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    open_round: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenRoundBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VotingState"];
                };
            };
        };
    };
    close_round: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VotingState"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDetail"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    audit_log: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
        };
    };
    revoke_invitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    revoke_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    set_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSprintBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintDetail"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
