import type { ConfigVars } from './lib/config'

/** Bindings plus optional secrets. `Env` itself is generated by `wrangler types`. */
export type AppEnv = Env & ConfigVars & { DB: D1Database; ROOMS: DurableObjectNamespace; ASSETS: Fetcher }
export type HonoEnv = { Bindings: AppEnv }
