import type { ConfigVars } from './lib/config'

/** Bindings plus optional secrets. `Env` itself is generated by `wrangler types`. */
export type AppEnv = Env & ConfigVars & {
  DB: D1Database
  ROOMS: DurableObjectNamespace
  ASSETS: Fetcher
  /**
   * Per-address limit on the signed-out paths, checked before D1 (lib/ratelimit.ts `edgeLimit`).
   * Optional: without it requests go through unchanged.
   */
  EDGE_LIMIT?: RateLimit
  /** The commit a release deployed (set by the release workflow's `wrangler deploy --var`). */
  MUNI_COMMIT?: string
}
export type HonoEnv = { Bindings: AppEnv }
