import type { ConfigVars } from './lib/config'

/** Bindings plus optional secrets. `Env` itself is generated by `wrangler types`. */
export type AppEnv = Env & ConfigVars & {
  DB: D1Database
  ROOMS: DurableObjectNamespace
  ASSETS: Fetcher
  /** The commit a release deployed (set by the release workflow's `wrangler deploy --var`). */
  MUNI_COMMIT?: string
}
export type HonoEnv = { Bindings: AppEnv }
