import { chromium } from '@playwright/test'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await browser.newPage()
page.on('pageerror', (e) => console.log('PAGEERROR', e.message))
page.on('console', (m) => console.log('CONSOLE', m.type(), m.text().slice(0, 300)))
const r = await page.goto('http://127.0.0.1:5173/signin')
console.log('status', r.status())
await page.waitForTimeout(2500)
console.log((await page.content()).slice(0, 1500))
await page.screenshot({ path: '/tmp/claude-0/-home-user-afterglow/6c8c67f9-2583-5880-90a9-bc1ffe1a46f5/scratchpad/shots/peek.png' })
await browser.close()
