// Drives the real app through the demo path and screenshots each screen.
import { chromium } from '@playwright/test'
const BASE = 'http://127.0.0.1:5173'
const API = 'http://127.0.0.1:8080'
const OUT = '/tmp/claude-0/-home-user-afterglow/6c8c67f9-2583-5880-90a9-bc1ffe1a46f5/scratchpad/shots'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const errors = []
async function signIn(ctx, email, name) {
  const page = await ctx.newPage()
  page.on('pageerror', (e) => errors.push(`[${email}] ${e.message}`))
  page.on('console', (m) => { if (m.type() === 'error') errors.push(`[${email}] console: ${m.text().slice(0, 200)}`) })
  await page.goto(`${BASE}/signin`)
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Your name').fill(name)
  await page.getByRole('button', { name: 'Email me a code' }).click()
  await page.getByLabel('Six-digit code').waitFor()
  const inbox = await (await fetch(`${API}/api/dev/inbox`)).json()
  const code = inbox.find((m) => m.to === email.toLowerCase()).subject.split(' ')[0]
  await page.getByLabel('Six-digit code').fill(code)
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.waitForURL((u) => !u.pathname.startsWith('/signin'))
  return page
}
const shot = (page, name, opts = {}) => page.screenshot({ path: `${OUT}/${name}.png`, fullPage: opts.full ?? false })

const desktop = await browser.newContext({ viewport: { width: 1440, height: 900 } })
const fac = await signIn(desktop, 'fay@example.com', 'Fay')
await shot(fac, '01-home-empty')
// seed demo through the UI's API (same cookies)
const seed = await fac.evaluate(async () => {
  const csrf = document.cookie.match(/muni_csrf=([^;]*)/)[1]
  const r = await fetch('/api/demo/seed', { method: 'POST', headers: { 'x-csrf-token': csrf, 'content-type': 'application/json' } })
  return r.json()
})
await fac.goto(`${BASE}/`)
await fac.waitForTimeout(500)
await shot(fac, '02-home')
await fac.goto(`${BASE}/workspaces/${seed.workspace_id}`)
await fac.waitForTimeout(800)
await shot(fac, '03-workspace', { full: true })
await fac.goto(`${BASE}/sprints/${seed.sprint_id}`)
await fac.waitForTimeout(800)
await shot(fac, '04-sprint-home-preparing', { full: true })
await fac.goto(`${BASE}/sprints/${seed.sprint_id}/prepare`)
await fac.waitForTimeout(800)
await shot(fac, '05-prepare-empty', { full: true })
// AI draft
await fac.getByRole('button', { name: 'Draft themes' }).click()
await fac.waitForTimeout(3500)
await shot(fac, '06-prepare-ai-draft', { full: true })
await fac.getByRole('button', { name: 'Use as starting point' }).click()
await fac.waitForTimeout(800)
await shot(fac, '07-prepare-grouped', { full: true })
// mark ready, start
await fac.getByRole('button', { name: 'Mark ready' }).click()
await fac.waitForTimeout(600)
await fac.getByRole('button', { name: 'Start the retro' }).click()
await fac.waitForURL(/stage/)
await fac.waitForTimeout(1000)
await shot(fac, '10-stage-arrive')
// mark everyone present from the stage
for (const name of ['Fay', 'Maya Reyes', 'Jonas Weber', 'Priya Nair']) { await fac.getByRole('button', { name: new RegExp('^' + name) }).click(); await fac.waitForTimeout(200) }
await shot(fac, '11-stage-arrive-present')
await fac.keyboard.press('ArrowRight'); await fac.waitForTimeout(700)
await shot(fac, '12-stage-remember')
await fac.keyboard.press('ArrowRight'); await fac.waitForTimeout(700)
await shot(fac, '13-stage-discover-sealed')
await fac.keyboard.press('r'); await fac.waitForTimeout(900)
await shot(fac, '14-stage-discover-revealed', { full: true })
await fac.getByRole('button', { name: 'Open voting' }).click(); await fac.waitForTimeout(600)
await fac.getByRole('button', { name: 'Vote for this' }).first().click(); await fac.waitForTimeout(400)
await shot(fac, '15-stage-voting')
await fac.getByRole('button', { name: 'Close voting and reveal totals' }).click(); await fac.waitForTimeout(600)
await fac.getByRole('button', { name: 'Set the top three as the agenda' }).click(); await fac.waitForTimeout(400)
await shot(fac, '16-stage-votes-closed', { full: true })
await fac.keyboard.press('ArrowRight'); await fac.waitForTimeout(700)
await shot(fac, '17-stage-discuss-agenda')
await fac.locator('li button').first().click(); await fac.waitForTimeout(800)
await fac.getByRole('button', { name: 'Invite someone' }).click(); await fac.waitForTimeout(500)
await shot(fac, '18-stage-discuss-topic', { full: true })
// participant companion on a phone
const phone = await browser.newContext({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true })
// a second participant needs an account that is in the sprint: use fay's phone as the same account (multi-device) for now
const phoneFay = await signIn(phone, 'fay@example.com', 'Fay')
await phoneFay.goto(`${BASE}/sprints/${seed.sprint_id}/room`)
await phoneFay.waitForTimeout(1000)
await shot(phoneFay, '19-companion-discuss', { full: true })
await phoneFay.getByRole('button', { name: 'Look around' }).click(); await phoneFay.waitForTimeout(300)
await shot(phoneFay, '20-companion-look-around', { full: true })
await phoneFay.getByRole('button', { name: 'Back to the live topic' }).click(); await phoneFay.waitForTimeout(300)
await phoneFay.getByPlaceholder('Something the room should know…').fill('One more angle: the outage overlapped with the release freeze.')
await phoneFay.getByRole('button', { name: 'Send' }).click(); await phoneFay.waitForTimeout(600)
await fac.getByRole('button', { name: 'Release new context' }).click(); await fac.waitForTimeout(700)
await shot(fac, '21-stage-context-released', { full: true })
await fac.keyboard.press('ArrowRight'); await fac.waitForTimeout(700)
await shot(fac, '22-stage-decide')
await fac.getByLabel(/What will we try/).fill('For the next sprint, name a first reviewer on every PR when it is opened.')
await fac.getByLabel(/How will we know/).fill('No PR waits more than one working day for a first comment.')
await fac.getByLabel(/Who accepts/).selectOption({ label: 'Maya Reyes' })
await fac.getByRole('button', { name: 'Propose this experiment' }).click(); await fac.waitForTimeout(700)
await shot(fac, '23-stage-decide-proposed', { full: true })
await fac.keyboard.press('ArrowRight'); await fac.waitForTimeout(700)
await shot(fac, '24-stage-leave', { full: true })
await fac.getByRole('button', { name: 'Complete the retro' }).click()
await fac.waitForURL(/outcomes/); await fac.waitForTimeout(900)
await shot(fac, '25-outcomes', { full: true })
// capture on phone for a collecting sprint: create a new sprint in the demo workspace
await fac.goto(`${BASE}/workspaces/${seed.workspace_id}/sprints/new`); await fac.waitForTimeout(800)
await shot(fac, '30-sprint-setup', { full: true })
await fac.getByLabel('Sprint name').fill('Sprint 43 — Search relevance')
await fac.getByRole('button', { name: 'Create sprint' }).click()
await fac.waitForURL(/\/sprints\/[0-9a-f-]+$/); await fac.waitForTimeout(600)
await shot(fac, '31-sprint-draft', { full: true })
await fac.getByRole('button', { name: 'Open this sprint for thoughts' }).first().click(); await fac.waitForTimeout(800)
await shot(fac, '32-sprint-collecting', { full: true })
await phoneFay.goto(`${BASE}/capture`); await phoneFay.waitForTimeout(900)
await shot(phoneFay, '33-capture-phone', { full: true })
await phoneFay.getByLabel('Your observation').fill('The flaky search test wasted most of Tuesday morning.')
await phoneFay.getByRole('radio', { name: 'Improve' }).click()
await phoneFay.getByRole('button', { name: 'Save the thought' }).click(); await phoneFay.waitForTimeout(900)
await shot(phoneFay, '34-capture-phone-saved', { full: true })
await fac.goto(`${BASE}/capture`); await fac.waitForTimeout(800)
await shot(fac, '35-capture-desktop', { full: true })
await fac.goto(`${BASE}/about`); await fac.waitForTimeout(500)
await shot(fac, '40-about', { full: true })
await fac.goto(`${BASE}/account`); await fac.waitForTimeout(500)
await shot(fac, '41-account', { full: true })
console.log('ERRORS:', errors.length ? errors : 'none')
await browser.close()
