/** The live stage: versioned commands, timer, attendance and the speaking round, context, notes, recovery. */
import { describe, expect, it } from 'vitest'
import { env } from 'cloudflare:test'
import { closeCollection, command, entry, get, go, ids, openSocket, patch, post, put, roomCancel, roomState, sleep, sprint, team, type User } from './harness'

/** A live sprint with `n` themes (one entry each) and everyone's attendance untouched. */
async function live(owner: User, members: User[], ws: string, n = 2, extra: Record<string, unknown> = {}) {
  const s = await sprint(owner, members, ws, 'collecting', extra)
  for (let i = 0; i < n; i++) await entry(members[i % members.length], s, 'improve', `entry ${i}`)
  const entries = await closeCollection(owner, s)
  const themes: string[] = []
  for (let i = 0; i < n; i++) {
    const g = await post(`/api/sprints/${s}/themes`, owner, { title: `Theme ${i}`, entry_ids: [entries[i].id] })
    themes.push(g.body.themes.find((t: { title: string }) => t.title === `Theme ${i}`).id)
  }
  expect((await go(owner, s, 'ready')).status).toBe(200)
  expect((await go(owner, s, 'live')).status).toBe(200)
  return { s, themes, entries }
}
const snap = (u: User, s: string) => get(`/api/sprints/${s}/meeting`, u)
const present = (u: User, s: string, ready?: boolean) => post(`/api/sprints/${s}/meeting/attendance`, u, ready === undefined ? { present: true } : { present: true, ready })
const raw = (u: User, s: string, expected_version: number, cmd: unknown) => post(`/api/sprints/${s}/meeting/command`, u, { expected_version, command: cmd })

describe('meeting', () => {
  it('rejects stale versions and lets exactly one of two conflicting commands win', async () => {
    const { owner, members, ws } = await team(1)
    const { s } = await live(owner, members, ws)
    const first = await snap(owner, s)
    expect(first.status).toBe(200)
    expect(first.body.version).toBe(1)
    expect(first.body.phase).toBe('arrive')
    const stale = await raw(owner, s, 0, { type: 'set_phase', phase: 'remember' })
    expect(stale.status).toBe(409)
    expect(stale.body.error).toContain('changed since you last saw it')
    expect((await snap(owner, s)).body.version).toBe(1)
    const [a, b] = await Promise.all([raw(owner, s, 1, { type: 'set_phase', phase: 'remember' }), raw(owner, s, 1, { type: 'set_phase', phase: 'discover' })])
    expect([a.status, b.status].sort()).toEqual([200, 409])
    const after = await snap(owner, s)
    expect(after.body.version).toBe(2)
    expect(after.body.phase).toBe(a.status === 200 ? 'remember' : 'discover')
    // Members never command; unknown phases and commands are 400.
    expect((await raw(members[0], s, 2, { type: 'set_phase', phase: 'discuss' })).status).toBe(403)
    expect((await raw(owner, s, 2, { type: 'set_phase', phase: 'lunch' })).status).toBe(400)
    expect((await raw(owner, s, 2, { type: 'teleport' })).status).toBe(400)
    expect((await snap(owner, s)).body.version).toBe(2)
    // Commands need a live sprint.
    const ready = await sprint(owner, members, ws, 'ready')
    expect((await raw(owner, ready, 1, { type: 'set_phase', phase: 'remember' })).status).toBe(409)
    expect((await snap(owner, ready)).status).toBe(404)
  })

  it('drives phases and a timer whose remaining time derives from one deadline', async () => {
    const { owner, members, ws } = await team(1)
    const { s } = await live(owner, members, ws)
    const phase = await command(owner, s, { type: 'set_phase', phase: 'remember' })
    expect(phase.status).toBe(200)
    expect(phase.body.phase).toBe('remember')
    expect(phase.body.phases).toEqual(['arrive', 'remember', 'discover', 'discuss', 'decide', 'leave'])
    expect(phase.body.timer.running).toBe(false)
    expect(phase.body.timer.remaining_secs).toBe(phase.body.plan.remember * 60)
    expect(phase.body.timer.total_secs).toBe(phase.body.plan.remember * 60)
    const started = await command(owner, s, { type: 'timer_start', secs: 120 })
    expect(started.body.timer.running).toBe(true)
    expect(started.body.timer.total_secs).toBe(120)
    expect(started.body.timer.remaining_secs).toBeGreaterThanOrEqual(118)
    expect(started.body.timer.remaining_secs).toBeLessThanOrEqual(120)
    const deadline = started.body.timer.ends_at as string
    expect(new Date(deadline).getTime() - new Date(started.body.server_time).getTime()).toBeGreaterThan(115_000)
    await sleep(1100)
    const later = await snap(members[0], s)
    expect(later.body.timer.ends_at).toBe(deadline)
    expect(later.body.timer.remaining_secs).toBeLessThan(started.body.timer.remaining_secs)
    expect(later.body.version).toBe(started.body.version)
    const paused = await command(owner, s, { type: 'timer_pause' })
    expect(paused.body.timer.running).toBe(false)
    expect(paused.body.timer.ends_at).toBeNull()
    const frozen = paused.body.timer.remaining_secs as number
    expect(frozen).toBeGreaterThanOrEqual(116)
    await sleep(300)
    expect((await snap(owner, s)).body.timer.remaining_secs).toBe(frozen)
    const resumed = await command(owner, s, { type: 'timer_resume' })
    expect(resumed.body.timer.running).toBe(true)
    expect(Math.abs(resumed.body.timer.remaining_secs - frozen)).toBeLessThanOrEqual(1)
    const adjusted = await command(owner, s, { type: 'timer_adjust', delta_secs: 60 })
    expect(adjusted.body.timer.remaining_secs).toBeGreaterThanOrEqual(frozen + 57)
    expect(adjusted.body.timer.total_secs).toBe(180)
    expect(new Date(adjusted.body.timer.ends_at).getTime()).toBeGreaterThan(new Date(deadline).getTime())
    const cleared = await command(owner, s, { type: 'timer_clear' })
    expect(cleared.body.timer).toEqual({ running: false, ends_at: null, remaining_secs: 0, total_secs: 0 })
    // Clamped inputs, plan edits, and a topic that budgets the discuss phase.
    expect((await command(owner, s, { type: 'timer_start', secs: 1 })).body.timer.total_secs).toBe(10)
    const plan = await command(owner, s, { type: 'set_plan', plan: { discuss: 30, arrive: 0 } })
    expect(plan.body.plan.discuss).toBe(30)
    expect(plan.body.plan.arrive).toBe(1)
    const topic = await command(owner, s, { type: 'set_topic', theme_id: plan.body.agenda[0].theme_id })
    expect(topic.body.current_theme_id).toBe(plan.body.agenda[0].theme_id)
    expect(topic.body.timer.total_secs).toBe(Math.floor((30 * 60) / 2))
    expect((await command(owner, s, { type: 'set_topic', theme_id: crypto.randomUUID() })).status).toBe(404)
  })

  it('runs quiet reading as a timed, self-clearing state', async () => {
    const { owner, members, ws } = await team(1)
    const { s } = await live(owner, members, ws)
    const quiet = await command(owner, s, { type: 'quiet_reading', secs: 30 })
    expect(quiet.status).toBe(200)
    expect(quiet.body.quiet_reading).toBe(true)
    expect(quiet.body.timer.running).toBe(true)
    expect(quiet.body.timer.total_secs).toBe(30)
    expect((await snap(members[0], s)).body.quiet_reading).toBe(true)
    expect((await command(owner, s, { type: 'set_phase', phase: 'discover' })).body.quiet_reading).toBe(false)
    // Lower bound of 15 seconds; clearing the timer ends it.
    expect((await command(owner, s, { type: 'quiet_reading', secs: 5 })).body.timer.total_secs).toBe(15)
    expect((await command(owner, s, { type: 'timer_clear' })).body.quiet_reading).toBe(false)
  })

  it('requires an explicit take_control while another controller is connected', async () => {
    const { owner, members, ws } = await team(1)
    const { s } = await live(owner, members, ws)
    const before = await snap(owner, s)
    expect(before.body.you_control).toBe(true)
    expect(before.body.controller_stale).toBe(true) // no socket yet
    const { socket, waitFor } = await openSocket(owner, s)
    await waitFor((m) => m.includes('"hello"'))
    expect((await snap(owner, s)).body.controller_stale).toBe(false)
    // Facilitation moves to a member while the old facilitator is still connected.
    expect((await patch(`/api/sprints/${s}`, owner, { facilitator_id: members[0].account_id })).status).toBe(200)
    const blocked = await command(members[0], s, { type: 'set_phase', phase: 'remember' })
    expect(blocked.status).toBe(409)
    expect(blocked.body.error).toContain('take control')
    expect((await snap(members[0], s)).body.you_control).toBe(false)
    const taken = await command(members[0], s, { type: 'take_control' })
    expect(taken.status).toBe(200)
    expect(taken.body.you_control).toBe(true)
    expect(taken.body.controller_name).toBe('Member 0')
    expect((await command(members[0], s, { type: 'set_phase', phase: 'remember' })).status).toBe(200)
    expect((await command(owner, s, { type: 'set_phase', phase: 'discover' })).status).toBe(403)
    socket.close()
  })

  it('rotates only through people who are present and ready', async () => {
    const { owner, members, ws } = await team(3)
    const { s } = await live(owner, members, ws)
    await present(members[0], s)
    await present(members[1], s, false)
    // members[2] never arrives.
    const view = await snap(owner, s)
    const att = (id: string) => view.body.attendance.find((a: { account_id: string }) => a.account_id === id)
    expect(att(members[0].account_id)).toMatchObject({ present: true, ready: true })
    expect(att(members[1].account_id)).toMatchObject({ present: true, ready: false })
    expect(att(members[2].account_id)).toMatchObject({ present: false })
    // Readiness is private: another member sees null for others, their own value for themselves.
    const asMember = await snap(members[1], s)
    expect(asMember.body.attendance.find((a: { is_you: boolean }) => a.is_you).ready).toBe(false)
    expect(asMember.body.attendance.find((a: { account_id: string }) => a.account_id === members[0].account_id).ready).toBeNull()
    const started = await command(owner, s, { type: 'speaking_start' })
    expect(started.body.speaking.status).toBe('active')
    expect(started.body.speaking.current.account_id).toBe(members[0].account_id)
    expect(started.body.speaking.remaining).toBe(0)
    expect((await roomState(s)).speaking.ordering).toEqual([members[0].account_id])
    expect((await snap(members[0], s)).body.speaking.current.is_you).toBe(true)
    const done = await command(owner, s, { type: 'speaking_next' })
    expect(done.body.speaking.status).toBe('exhausted')
    expect(done.body.speaking.current).toBeNull()
    const again = await command(owner, s, { type: 'speaking_next' })
    expect(again.status).toBe(409)
    expect(again.body.error).toContain('no speaking round is active')
    expect((await command(owner, s, { type: 'speaking_end' })).body.speaking).toBeNull()
  })

  it('pass removes the current speaker at once and keeps them out until they are ready again', async () => {
    const { owner, members, ws } = await team(2)
    const { s } = await live(owner, members, ws)
    await present(members[0], s)
    await present(members[1], s)
    const started = await command(owner, s, { type: 'speaking_start' })
    const currentId = started.body.speaking.current.account_id as string
    const passer = members.find((m) => m.account_id === currentId)!
    const other = members.find((m) => m.account_id !== currentId)!
    const passed = await post(`/api/sprints/${s}/meeting/pass`, passer)
    expect(passed.status).toBe(200)
    expect(passed.body.speaking.current.account_id).toBe(other.account_id)
    expect(passed.body.attendance.find((a: { is_you: boolean }) => a.is_you).ready).toBe(false)
    expect(passed.body.version).toBe(started.body.version + 1)
    // The passer is not re-selected: after the other person, the round is exhausted.
    const next = await command(owner, s, { type: 'speaking_next' })
    expect(next.body.speaking.status).toBe('exhausted')
    // Passing while not the current speaker only steps out of the rotation.
    await command(owner, s, { type: 'speaking_end' })
    await post(`/api/sprints/${s}/meeting/attendance`, passer, { ready: true })
    const round2 = await command(owner, s, { type: 'speaking_start' })
    expect((await roomState(s)).speaking.ordering).toHaveLength(2)
    const notCurrent = members.find((m) => m.account_id !== round2.body.speaking.current.account_id)!
    const quiet = await post(`/api/sprints/${s}/meeting/pass`, notCurrent)
    expect(quiet.body.speaking.current.account_id).toBe(round2.body.speaking.current.account_id)
    expect((await command(owner, s, { type: 'speaking_next' })).body.speaking.status).toBe('exhausted')
    // Passing outside a live retro is a 404 from the room.
    const ready = await sprint(owner, members, ws, 'ready')
    expect((await post(`/api/sprints/${ready}/meeting/pass`, members[0])).status).toBe(404)
  })

  it('skips someone who left and appends a late arrival without reordering others', async () => {
    const { owner, members, ws } = await team(3)
    const { s } = await live(owner, members, ws)
    await present(members[0], s)
    await present(members[1], s)
    await present(members[2], s)
    await command(owner, s, { type: 'speaking_start' })
    const ordering = (await roomState(s)).speaking.ordering as string[]
    expect(ordering).toHaveLength(3)
    const [first, second, third] = ordering.map((id) => members.find((m) => m.account_id === id)!)
    expect((await snap(owner, s)).body.speaking.current.account_id).toBe(first.account_id)
    // The second person leaves before their turn.
    const left = await post(`/api/sprints/${s}/meeting/attendance`, second, { present: false })
    expect(left.body.speaking.current.account_id).toBe(first.account_id)
    const next = await command(owner, s, { type: 'speaking_next' })
    expect(next.body.speaking.current.account_id).toBe(third.account_id)
    expect(next.body.speaking.remaining).toBe(0)
    expect((await command(owner, s, { type: 'speaking_next' })).body.speaking.status).toBe('exhausted')
    await command(owner, s, { type: 'speaking_end' })

    // Late arrival: a fresh round with two people; a third arrives after it started.
    const late = await team(3)
    const { s: l } = await live(late.owner, late.members, late.ws)
    await present(late.members[0], l)
    await present(late.members[1], l)
    const startedLate = await command(late.owner, l, { type: 'speaking_start' })
    expect(startedLate.status, JSON.stringify(startedLate.body)).toBe(200)
    const before = (await roomState(l)).speaking.ordering as string[]
    expect(before).toHaveLength(2)
    await present(late.members[2], l)
    expect((await roomState(l)).speaking.ordering).toEqual(before)
    const n1 = await command(late.owner, l, { type: 'speaking_next' })
    expect(n1.body.speaking.current.account_id).toBe(before[1])
    expect(n1.body.speaking.remaining).toBe(1)
    const after = (await roomState(l)).speaking.ordering as string[]
    expect(after.slice(0, 2)).toEqual(before)
    expect(after[2]).toBe(late.members[2].account_id)
    const n2 = await command(late.owner, l, { type: 'speaking_next' })
    expect(n2.body.speaking.current.account_id).toBe(late.members[2].account_id)
    expect((await command(late.owner, l, { type: 'speaking_next' })).body.speaking.status).toBe('exhausted')
    // The facilitator can mark presence for others, never readiness.
    expect((await post(`/api/sprints/${l}/meeting/attendance/${late.members[0].account_id}`, late.owner, { present: false, ready: false })).status).toBe(200)
    const v = await snap(late.owner, l)
    expect(v.body.attendance.find((a: { account_id: string }) => a.account_id === late.members[0].account_id)).toMatchObject({ present: false, ready: true })
    expect((await post(`/api/sprints/${l}/meeting/attendance/${late.members[0].account_id}`, late.members[1], { present: true })).status).toBe(403)
    expect((await post(`/api/sprints/${l}/meeting/attendance/${crypto.randomUUID()}`, late.owner, { present: true })).status).toBe(404)
  })

  it('excludes the facilitator from the rotation unless the sprint says otherwise', async () => {
    const { owner, members, ws } = await team(1)
    const { s } = await live(owner, members, ws)
    await present(owner, s)
    await present(members[0], s)
    const excluded = await command(owner, s, { type: 'speaking_start' })
    expect(excluded.body.include_facilitator_in_rotation).toBe(false)
    expect((await roomState(s)).speaking.ordering).toEqual([members[0].account_id])
    await command(owner, s, { type: 'speaking_end' })
    // Only the facilitator present: nothing to rotate through.
    await post(`/api/sprints/${s}/meeting/attendance`, members[0], { present: false })
    expect((await command(owner, s, { type: 'speaking_start' })).body.speaking.status).toBe('exhausted')
    await command(owner, s, { type: 'speaking_end' })
    expect((await patch(`/api/sprints/${s}`, owner, { include_facilitator_in_rotation: true })).status).toBe(200)
    await present(members[0], s)
    const included = await command(owner, s, { type: 'speaking_start' })
    expect(included.body.include_facilitator_in_rotation).toBe(true)
    expect(included.body.speaking.status).toBe('active')
    expect([...(await roomState(s)).speaking.ordering].sort()).toEqual([owner.account_id, members[0].account_id].sort())
  })

  it('collects context privately and reveals it under the theme only on release', async () => {
    const { owner, members, ws } = await team(2)
    const { s, themes } = await live(owner, members, ws)
    const add = (u: User, body: Record<string, unknown>) => post(`/api/sprints/${s}/meeting/context`, u, body)
    expect((await add(members[0], { theme_id: crypto.randomUUID(), body: 'x' })).status).toBe(404)
    expect((await add(members[0], { theme_id: themes[0], body: '   ' })).status).toBe(400)
    const key = crypto.randomUUID()
    const one = await add(members[0], { theme_id: themes[0], body: 'ctx-needle', idempotency_key: key })
    expect(one.status).toBe(200)
    const two = await add(members[0], { theme_id: themes[0], body: 'ctx-needle', idempotency_key: key })
    expect(two.status).toBe(200)
    expect(two.body.my_context).toHaveLength(1)
    expect(two.body.my_context[0]).toMatchObject({ theme_id: themes[0], body: 'ctx-needle', released: false })
    const n = await env.DB.prepare('SELECT count(*) AS n FROM context_additions WHERE sprint_id = ?').bind(s).first<{ n: number }>()
    expect(n!.n).toBe(1)
    // Invisible to others until release; the facilitator only learns that something waits.
    expect((await snap(members[1], s)).body.my_context).toEqual([])
    expect((await snap(members[1], s)).body.has_unreleased_context).toBeNull()
    expect((await snap(owner, s)).body.has_unreleased_context).toBe(true)
    const themesBefore = await get(`/api/sprints/${s}/themes`, members[1])
    expect(themesBefore.body.themes.find((t: { id: string }) => t.id === themes[0]).context).toEqual([])
    expect(JSON.stringify(themesBefore.body)).not.toContain('ctx-needle')
    expect((await command(members[1], s, { type: 'release_context' })).status).toBe(403)
    const released = await command(owner, s, { type: 'release_context' })
    expect(released.status).toBe(200)
    expect(released.body.has_unreleased_context).toBe(false)
    const themesAfter = await get(`/api/sprints/${s}/themes`, members[1])
    const ctx = themesAfter.body.themes.find((t: { id: string }) => t.id === themes[0]).context
    expect(ctx).toHaveLength(1)
    expect(ctx[0].body).toBe('ctx-needle')
    expect(Object.keys(ctx[0]).sort()).toEqual(['body', 'id'])
    expect((await snap(members[0], s)).body.my_context[0].released).toBe(true)
    // Context is a live-only affordance.
    const ready = await sprint(owner, members, ws, 'ready')
    expect((await add(members[0], { theme_id: themes[0], body: 'nope' })).status).toBe(200) // still live here
    expect((await post(`/api/sprints/${ready}/meeting/context`, members[0], { theme_id: themes[0], body: 'nope' })).status).toBe(409)
  })

  it('stores the facilitator’s takeaway and notes per theme, merging partial updates', async () => {
    const { owner, members, ws } = await team(1)
    const { s, themes } = await live(owner, members, ws)
    expect((await put(`/api/sprints/${s}/meeting/notes/${themes[0]}`, members[0], { takeaway: 'no' })).status).toBe(403)
    expect((await put(`/api/sprints/${s}/meeting/notes/${crypto.randomUUID()}`, owner, { takeaway: 'no' })).status).toBe(404)
    await command(owner, s, { type: 'set_topic', theme_id: themes[0] })
    const saved = await put(`/api/sprints/${s}/meeting/notes/${themes[0]}`, owner, { takeaway: 'We agreed to pair on reviews', notes: 'long discussion' })
    expect(saved.status).toBe(200)
    expect(saved.body.notes).toMatchObject({ takeaway: 'We agreed to pair on reviews', notes: 'long discussion', impact: '', discussed: false })
    const partial = await put(`/api/sprints/${s}/meeting/notes/${themes[0]}`, owner, { impact: 'fewer stalls' })
    expect(partial.body.notes).toMatchObject({ takeaway: 'We agreed to pair on reviews', notes: 'long discussion', impact: 'fewer stalls' })
    const g = await get(`/api/sprints/${s}/themes`, members[0])
    expect(g.body.themes.find((t: { id: string }) => t.id === themes[0]).takeaway).toBe('We agreed to pair on reviews')
    expect(g.body.themes.find((t: { id: string }) => t.id === themes[0]).discussed).toBe(false)
    const marked = await command(owner, s, { type: 'mark_discussed', theme_id: themes[0], discussed: true })
    expect(marked.body.discussed_theme_ids).toEqual([themes[0]])
    expect(marked.body.notes.discussed).toBe(true)
    expect((await get(`/api/sprints/${s}/themes`, members[0])).body.themes.find((t: { id: string }) => t.id === themes[0]).discussed).toBe(true)
    // Notes for a theme that isn't the current topic are kept but not shown on stage.
    await put(`/api/sprints/${s}/meeting/notes/${themes[1]}`, owner, { takeaway: 'other' })
    expect((await snap(owner, s)).body.notes.takeaway).toBe('We agreed to pair on reviews')
  })

  it('serves one authoritative snapshot to everyone and re-initialises a wiped room', async () => {
    const { owner, members, ws } = await team(2)
    const { s } = await live(owner, members, ws)
    await command(owner, s, { type: 'set_phase', phase: 'remember' })
    await command(owner, s, { type: 'timer_start', secs: 300 })
    const a = await snap(owner, s)
    const b = await snap(members[0], s)
    const c = await snap(members[1], s)
    for (const v of [b, c]) {
      expect(v.status).toBe(200)
      expect(v.body.version).toBe(a.body.version)
      expect(v.body.session_id).toBe(a.body.session_id)
      expect(v.body.phase).toBe('remember')
      expect(v.body.timer.ends_at).toBe(a.body.timer.ends_at)
      expect(v.body.agenda).toEqual(a.body.agenda)
      expect(v.body.is_facilitator).toBe(false)
    }
    expect(a.body.version).toBe(3)
    // The room forgets its session (e.g. a failed start): the next read rebuilds a fresh one from D1.
    await roomCancel(s)
    const fresh = await snap(members[0], s)
    expect(fresh.status).toBe(200)
    expect(fresh.body.version).toBe(1)
    expect(fresh.body.phase).toBe('arrive')
    expect(fresh.body.cancelled).toBe(false)
    expect(fresh.body.ended_at).toBeNull()
    expect(fresh.body.timer.running).toBe(false)
    expect(fresh.body.agenda).toEqual(a.body.agenda)
    expect((await snap(owner, s)).body.version).toBe(1)
    expect((await get(`/api/sprints/${s}`, owner)).body.status).toBe('live')
    // Cancelling the session from the lifecycle (live → ready) ends it; going live again starts a fresh one.
    await command(owner, s, { type: 'set_phase', phase: 'discuss' })
    expect((await go(owner, s, 'ready')).status).toBe(200)
    const cancelled = await snap(owner, s)
    expect(cancelled.status).toBe(200)
    expect(cancelled.body.cancelled).toBe(true)
    expect(cancelled.body.ended_at).not.toBeNull()
    expect((await get(`/api/sprints/${s}`, owner)).body.session_cancelled).toBe(true)
    expect((await command(owner, s, { type: 'set_phase', phase: 'arrive' })).status).toBe(409)
    expect((await go(owner, s, 'live')).status).toBe(200)
    const restarted = await snap(owner, s)
    expect(restarted.body.version).toBe(1)
    expect(restarted.body.cancelled).toBe(false)
    expect(restarted.body.phase).toBe('arrive')
    expect((await go(owner, s, 'completed')).status).toBe(200)
    const ended = await snap(members[0], s)
    expect(ended.status).toBe(200)
    expect(ended.body.ended_at).not.toBeNull()
    expect(ended.body.phase).toBe('leave')
    expect((await command(owner, s, { type: 'set_phase', phase: 'arrive' })).status).toBe(409)
  })

  it('validates agenda items against the sprint’s themes', async () => {
    const { owner, members, ws } = await team(1)
    const { s, themes } = await live(owner, members, ws)
    const r = await command(owner, s, { type: 'set_agenda', items: [{ theme_id: themes[1], reason: 'most votes' }, { theme_id: crypto.randomUUID() }, { theme_id: themes[0] }] })
    expect(r.status).toBe(200)
    expect(r.body.agenda).toEqual([{ theme_id: themes[1], reason: 'most votes' }, { theme_id: themes[0], reason: null }])
    void ids
  })
})
